# Generated by Django 5.0.7 on 2025-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_of_copies', models.IntegerField(default=1)),
                ('author', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
    ]
